server:
  port: 8089
  servlet:
    context-path: /${spring.application.name}
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  application:
    name: suifeng-demo

  messages:
    # 国际化资源文件路径
    basename: i18n/messages

  # 日期格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  mvc:
    view:
      suffix: .html
    throw-exception-if-no-handler-found: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # 开启静态资源缓存，通过资源的MD5生成版本号
#  resources:
#    chain:
#      cache: true
#      enabled: true
#      compressed: true
#        strategy:
#        content:
#          enabled: true
#          paths: /**

  thymeleaf:
    enabled: false
    prefix: classpath:/views/
    # 禁用缓存
    cache: false

#################api conf begin####################
api:
  # 接口配置
  rest:
    enabled: true
    server-addr:
      primary: localhost:8080/tzydb
      pt1: localhost:8081/tzydb
      pt2: localhost:8089/suifeng-demo
    http:
      max-conn-total: 1000
      max-conn-per-route: 1000
      connect-timeout: 3000
      read-timeout: 30000

  # 返回体配置
  result:
    enabled: true

  # 统一异常配置
  exception:
    type: admin

  # 接口文档配置
  swagger:
    enabled: false
    title: suifeng-demo
    description: suifeng-demo
    version: 1.0.0
    base-package:
    base-path:
    exclude-path:
    host: localhost:${server.port}/${spring.application.name}/doc.html
#################api conf end####################

resource:
  resourceHandler:
    '[doc.html]': classpath:/META-INF/resources/
    '[/webjars/**]': classpath:/META-INF/resources/webjars/
    '[/**]': classpath:/META-INF/resources/static/,classpath:/static/

# 验证码
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1

# jasypt加密的密匙
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7